-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
(
    SELECT 
        DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        A.SALES_DATE AS SALES_DATE_RAW,
        A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT, A.ONLINE_SALE_ID AS SALE_ID
    FROM ONLINE_SALE A
    UNION
    SELECT
        DATE_FORMAT(B.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        B.SALES_DATE AS SALES_DATE_RAW,
    B.PRODUCT_ID, null as USER_ID, B.SALES_AMOUNT, B.OFFLINE_SALE_ID AS SALE_ID
    FROM OFFLINE_SALE B
) AS C
WHERE DATE_FORMAT(C.SALES_DATE_RAW, '%Y%m') = '202203'
ORDER BY C.SALES_DATE, C.PRODUCT_ID, C.USER_ID